spring:
  application:
    name: todo-list-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop

secret_key: abcddafdafadfadfdsfadfaddsafasdfdasf
access_token_expiry_time: 1800
refresh_token_expiry_time: 7200